USE test_block
GO

-- READ UNCOMMITED
BEGIN TRAN;
	UPDATE dbo.t1
		SET Price = Price + 1.00
	WHERE ID = 2;
SELECT ID, Price FROM dbo.t1 WHERE ID = 2;

ROLLBACK TRAN;
SELECT ID, Price FROM dbo.t1 WHERE ID = 2;
/*Это был пример грязного чтения*/

-- READ COMMITTED
BEGIN TRAN;
	UPDATE dbo.t1
		SET Price = Price + 1.00
	WHERE ID = 2;
SELECT ID, Price FROM dbo.t1 WHERE ID = 2;

ROLLBACK TRAN;

-- REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRAN;
SELECT ID, Price FROM dbo.t1 WHERE ID = 2;

SELECT ID, Price FROM dbo.t1 WHERE ID = 2;
COMMIT TRAN;

-- SERIALIZABLE
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRAN;
	SELECT ID, Name, Price, Discount
	FROM dbo.t1
	WHERE Discount < 0.20;

SELECT ID, Name, Price, Discount
FROM dbo.t1
WHERE Discount < 0.20;
COMMIT TRAN;

-- SNAPSHOT
ALTER DATABASE test_block SET ALLOW_SNAPSHOT_ISOLATION ON;

BEGIN TRAN;
	SELECT ID, Price FROM dbo.t1 WHERE ID = 2;
UPDATE dbo.t1
	SET Price = Price + 1.00
WHERE ID = 2;
	SELECT ID, Price FROM dbo.t1 WHERE ID = 2;

COMMIT TRAN;

-- Step 1
SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
BEGIN TRAN;
	SELECT ID, Price FROM dbo.t1 WHERE ID = 2;

-- Step 2
UPDATE dbo.t1
	SET Price = 20.00
WHERE ID = 2;
COMMIT TRAN;

-- READ COMMITTED SNAPSHOT

ALTER DATABASE test_block SET READ_COMMITTED_SNAPSHOT ON;

BEGIN TRAN;
	SELECT ID,	Price FROM dbo.t1 WHERE ID = 2;
UPDATE dbo.t1
	SET Price = Price + 1.00
WHERE ID = 2;
	SELECT ID, Price FROM dbo.t1 WHERE ID = 2;

COMMIT TRAN;