CREATE DATABASE MyDB
ON
PRIMARY
(NAME = N'MyDB_Prm',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MyDB_Prm.mdf',
SIZE = 4096KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1024KB),

FILEGROUP SECONDARY
(NAME = N'MyDB_FG1_1', 
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MyDB_FG1_1.ndf',
SIZE = 1024KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1024KB),

(NAME = N'MyDB_FG1_2', 
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MyDB_FG1_2.ndf',
SIZE = 1024KB,
MAXSIZE = UNLIMITED,
FILEGROWTH = 1024KB)

LOG ON
(NAME = N'MyDB_log',
FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MyDB_log.ldf',
SIZE = 1024KB,
MAXSIZE = 2048GB,
FILEGROWTH = 10%)
COLLATE SQL_Latin1_General_CP1_CI_AS
GO